#!/usr/bin/env node
// @aliou/pi-harness patch manifest sync.
//
// `patches/manifest.json` is the source of truth: it lists, per package, the
// ordered patch directories to apply. pnpm cannot express that — its
// `pnpm.patchedDependencies` map takes exactly one patch file per
// `package@version` — so this script flattens each package's patches, in
// manifest order, into a single generated diff under `patches/combined/` and
// points `patchedDependencies` at it.
//
// Consumers:
//   - pnpm (`pnpm -C patches install`) applies the combined diff.
//   - Nix (`pkgs/pi-cli-patched`) reads the manifest and applies each patch in
//     succession, so a failure names the individual patch.
//
// Because patches for one package are concatenated, two patches for the same
// package must not touch the same file. This script rejects that.
//
// Usage:
//   node scripts/sync-patches.mjs           # regenerate combined diffs + package.json
//   node scripts/sync-patches.mjs --check   # fail if anything is out of date

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Resolved from this file, not the cwd, so running the script by absolute path
// from another checkout cannot rewrite or delete that checkout's patches.
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PATCHES_DIR = path.join(REPO_ROOT, "patches");
const MANIFEST_FILE = path.join(PATCHES_DIR, "manifest.json");
const PKG_FILE = path.join(PATCHES_DIR, "package.json");
const COMBINED_DIR = path.join(PATCHES_DIR, "combined");
const COMBINED_REL = "combined";

const check = process.argv.includes("--check");
const problems = [];
const fail = (message) => problems.push(message);

const manifest = JSON.parse(readFileSync(MANIFEST_FILE, "utf8"));
const pkg = JSON.parse(readFileSync(PKG_FILE, "utf8"));
const packages = Object.entries(manifest).filter(([key]) => !key.startsWith("//"));

/**
 * Files a unified diff touches, from its paired `--- a/x` / `+++ b/x` headers.
 *
 * Only a `+++` immediately preceded by a `---` is a header; payload lines can
 * legitimately start with `+++ ` (an added line whose text begins with `++ `).
 * Both sides are recorded so a rename conflicts with a patch that edits either
 * pathname, and `/dev/null` is ignored so two unrelated file deletions do not
 * look like a collision.
 */
function targetsOf(diff) {
  const clean = (header) => header.slice(4).trim().split("\t")[0].replace(/^[ab]\//, "");
  const lines = diff.split("\n");
  const targets = new Set();
  for (let i = 0; i + 1 < lines.length; i++) {
    if (!lines[i].startsWith("--- ") || !lines[i + 1].startsWith("+++ ")) continue;
    for (const side of [clean(lines[i]), clean(lines[i + 1])]) {
      if (side !== "/dev/null") targets.add(side);
    }
    i++;
  }
  return [...targets];
}

/** Every patch dir on disk, so orphans (present but unlisted) are caught. */
const dirsOnDisk = new Set(
  readdirSync(PATCHES_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(path.join(PATCHES_DIR, e.name, "patch.diff")))
    .map((e) => e.name),
);

const combined = new Map();
const patchedDependencies = {};

for (const [pkgName, dirs] of packages) {
  const version = pkg.dependencies?.[pkgName];
  if (!version) {
    fail(`${pkgName}: listed in manifest.json but not in patches/package.json dependencies`);
    continue;
  }

  const seenTargets = new Map();
  const parts = [];
  for (const dir of dirs) {
    const file = path.join(PATCHES_DIR, dir, "patch.diff");
    if (!existsSync(file)) {
      fail(`${pkgName}: ${dir}/patch.diff is missing`);
      continue;
    }
    dirsOnDisk.delete(dir);

    const diff = readFileSync(file, "utf8");
    for (const target of targetsOf(diff)) {
      const owner = seenTargets.get(target);
      if (owner) {
        fail(`${pkgName}: ${dir} and ${owner} both patch ${target}; concatenated patches must touch distinct files`);
      }
      seenTargets.set(target, dir);
    }
    parts.push(`# ${dir}\n${diff.endsWith("\n") ? diff : `${diff}\n`}`);
  }

  const slug = pkgName.replace(/^@[^/]+\//, "");
  const rel = `${COMBINED_REL}/${slug}.diff`;
  combined.set(rel, `# Generated by scripts/sync-patches.mjs from patches/manifest.json. Do not edit.\n${parts.join("")}`);
  patchedDependencies[`${pkgName}@${version}`] = rel;
}

for (const orphan of dirsOnDisk) {
  fail(`${orphan}/patch.diff exists but is not listed in patches/manifest.json`);
}

if (problems.length > 0) {
  for (const problem of problems) console.error(`error: ${problem}`);
  process.exit(1);
}

if (check) {
  let stale = 0;
  for (const [rel, content] of combined) {
    const file = path.join(PATCHES_DIR, rel);
    if (!existsSync(file) || readFileSync(file, "utf8") !== content) {
      console.error(`error: patches/${rel} is out of date`);
      stale++;
    }
  }
  if (JSON.stringify(pkg.pnpm?.patchedDependencies ?? {}) !== JSON.stringify(patchedDependencies)) {
    console.error("error: patches/package.json pnpm.patchedDependencies is out of date");
    stale++;
  }
  if (stale > 0) {
    console.error("\nrun `pnpm patches:sync` and commit the result");
    process.exit(1);
  }
  console.log("patches are in sync");
  process.exit(0);
}

rmSync(COMBINED_DIR, { recursive: true, force: true });
mkdirSync(COMBINED_DIR, { recursive: true });
for (const [rel, content] of combined) {
  writeFileSync(path.join(PATCHES_DIR, rel), content);
  console.log(`wrote patches/${rel}`);
}

pkg.pnpm = { ...pkg.pnpm, patchedDependencies };
writeFileSync(PKG_FILE, `${JSON.stringify(pkg, null, 2)}\n`);
console.log("updated patches/package.json pnpm.patchedDependencies");
